version: '3.6'

services:
  client:
    ports:
      - 3000:3000
    depends_on:
      - api
    build:
      context: ../client
      dockerfile: ./Dockerfile
    volumes:
      - ../client/pages:/app/pages
      - ../client/utils:/app/utils
      - ../client/components:/app/components
      - ../client/public:/app/public:cached
    working_dir: /app
