version: '3.6'

services:
  client:
    ports:
      - 3000:3000
    depends_on:
      - api
    build:
      context: ../client
    env_file: ../client/.env
    volumes:
      - ../client/adapters:/app/adapters
      - ../client/pages:/app/pages
      - ../client/utils:/app/utils
      - ../client/components:/app/components
      - ../client/public:/app/public:cached
